### ISSUE TITLE
Upgrade commons-codec version

### ISSUE THREAD

**Issue by ekozo-tgu** [snowplow/snowplow-java-tracker#172]
`http://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Base64.html#encodeBase64String` (used at com.snowplowanalytics.snowplow.tracker.Utils.base64Encode(Utils.java:111))  is included in commons-codec since 1.4 and build.gradle of snowplow-java-tracker is requiring v 1.2

That is causing `java.lang.NoSuchMethodError` exception:
```
| Error java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64String([B)Ljava/lang/String;
| Error         at com.snowplowanalytics.snowplow.tracker.Utils.base64Encode(Utils.java:111)
| Error         at com.snowplowanalytics.snowplow.tracker.payload.TrackerPayload.addMap(TrackerPayload.java:91)
| Error         at com.snowplowanalytics.snowplow.tracker.events.Unstructured.getPayload(Unstructured.java:90)
| Error         at com.snowplowanalytics.snowplow.tracker.Tracker.track(Tracker.java:269)
| Error         at com.snowplowanalytics.snowplow.tracker.Tracker$track.call(Unknown Source)
....
```

**Comment by alexanderdean** [comment]
Thanks for raising @ekozo-tgu !
